### ISSUE TITLE
How to use docker-compose instead of docker run

### ISSUE THREAD

**Issue by ovizii** [zhtengw/kodexplorer-plugins#10]
Your example was this:
`docker run --name onlyoffice --restart always -i -t -d -p 8000:80 onlyoffice/documentserver `

Here is my try to get this working via docker-compose, does this look right?
```
    onlyoffice:
        container_name: onlyoffice
        hostname: onlyoffice
        image: onlyoffice/documentserver:latest
        networks:
          - kodexplorer_network
        restart: "always"
        ports:
            - "8000:80"
        stdin_open: true
        tty: true
        logging:
          driver: "json-file"
          options:
            max-size: "200k"
            max-file: "10"
```

My problem is that I then configured the plugin like this:
![image](https://user-images.githubusercontent.com/837902/80969188-8088d880-8e19-11ea-8582-21a93069a8c5.png)

but if I open an Office file I get:
![image](https://user-images.githubusercontent.com/837902/80969342-b8901b80-8e19-11ea-86c5-e6822230b065.png)

Any help on how to debug the problem? The 172.21.0.3 is correct as from my docker host I can curl curl -I  http://172.21.0.3:8000/web-apps/apps/api/documents/api.js

**Comment by ovizii** [comment]
This should be correct, seeing the official sample file: https://raw.githubusercontent.com/ONLYOFFICE/Docker-CommunityServer/master/docker-compose.yml

**Comment by zhtengw** [comment]
I think you access your kodexplorer with “https” address. If that being so you should configure your onlyOffice to be accessed with https, and fill the https api.

**Comment by zhtengw** [comment]
Maybe the description in the plugin configure page is confusing. I am going to update it with:
```
The address of the OnlyOffice API must be the same protocol as the address where KodExplorer is deployed.
If KodExplorer is an http site, the "http address" of the OnlyOffice API cannot be empty. The https is the same.
In addition, if the port onlyoffice used is not 80 or 443, you need to specify the port number.
```
I hope I made the description clear.

**Comment by ovizii** [comment]
thanks for trying to help. Now using https I get a blank page when trying to access the office editor

![image](https://user-images.githubusercontent.com/837902/80986407-cf8e3800-8e30-11ea-99a8-79a1fbedb223.png)

btw. my kodexplorer is behind traefik as a reverse proxy. does that change anything?

**Comment by ovizii** [comment]
> Maybe the description in the plugin configure page is confusing. I am going to update it with:
> 
> ```
> The address of the OnlyOffice API must be the same protocol as the address where KodExplorer is deployed.
> If KodExplorer is an http site, the "http address" of the OnlyOffice API cannot be empty. The https is the same.
> In addition, if the port onlyoffice used is not 80 or 443, you need to specify the port number.
> ```
> 
> I hope I made the description clear.

I'm really struggling to understand. I need to use the protocol I use to access kodexplorer, in my case http BUT the IP address or hostname of the onlyoffice container followed by the port of the kodexplorer or the onlyoffice container?

**Comment by zhtengw** [comment]
If the page is blank, the console of your web brower will give you some tips. Press F12 to show the console.

**Comment by zhtengw** [comment]
> 
> 
> > Maybe the description in the plugin configure page is confusing. I am going to update it with:
> > ```
> > The address of the OnlyOffice API must be the same protocol as the address where KodExplorer is deployed.
> > If KodExplorer is an http site, the "http address" of the OnlyOffice API cannot be empty. The https is the same.
> > In addition, if the port onlyoffice used is not 80 or 443, you need to specify the port number.
> > ```
> > 
> > 
> > I hope I made the description clear.
> 
> I'm really struggling to understand. I need to use the protocol I use to access kodexplorer, in my case http BUT the IP address or hostname of the onlyoffice container followed by the port of the kodexplorer or the onlyoffice container?

The same protocol means both addresses of KodExplorer and OnlyOffice Server are started with "http" or "https". For example, the KodExplorer site is "http://kodhost.com/kodexplorer", then OnlyOffice Server address should start with "http://". And if the KodExplorer site is "https://kodhost.com/kodexplorer", then OnlyOffice Server address should start with "https://".

**Comment by zhtengw** [comment]
I am not a native english speaker. I am sorry if my words make you confusing. I will try my best to explain.

**Comment by ovizii** [comment]
> I am not a native english speaker. I am sorry if my words make you confusing. I will try my best to explain.
Hey, don't worry, I'm not a native English speaker either, maybe its my fault I am not understanding the instructions :-) I'm very happy that you are trying to help me so lets see if we can solve it. 

Lets see if we can solve this if I post my docker-compose file.

So, I access my kodexplorer via https://files.local.my.tld (this is a publicly reachable URL)
This lands me at a traefik container using https which in turn connects to the kodexplorer container on port 80. 
Since kodexplorer and onlyoffice containers have their hostname set and are in the same network I should be able to use the hostname or their internal private IP. I already tried both.

```
    kodexplorer:
        container_name: kodexplorer
        hostname: kodexplorer
        image: xaljer/kodexplorer:latest
        networks:
          - traefik_network
          - kodexplorer_network
        restart: "no"
        expose:
          - 80
        volumes:
          - '/my/path/kodexplorer:/var/www/html'
          - '/my/path:/var/www/html/data/User/admin/home/some-folder'
          - '/etc/timezone:/etc/timezone:ro'
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.http.routers.kodexplorer.tls=true"
            - "traefik.http.routers.kodexplorer.entrypoints=https"
            - "traefik.http.routers.kodexplorer.tls.certresolver=cloudflare"
            - "traefik.http.routers.kodexplorer.rule=Host(`files.local.my.tld`)"
            - "traefik.http.services.kodexplorer.loadbalancer.server.port=80"
            - "traefik.http.routers.kodexplorer.service=kodexplorer"
        logging:
          driver: "json-file"
          options:
            max-size: "200k"
            max-file: "10"


    onlyoffice:
        container_name: onlyoffice
        hostname: onlyoffice
        image: onlyoffice/documentserver:latest
        networks:
          - kodexplorer_network
        restart: "no"
        ports:
            - "8000:80"
        volumes:
          - '/etc/timezone:/etc/timezone:ro'
        stdin_open: true
        tty: true
        logging:
          driver: "json-file"
          options:
            max-size: "200k"
            max-file: "10"
```

What should this look like?
![image](https://user-images.githubusercontent.com/837902/81006283-88636f80-8e4f-11ea-8372-624dd357e8b2.png)

![image](https://user-images.githubusercontent.com/837902/81006333-a16c2080-8e4f-11ea-90d6-3e4c62b51663.png)


I tried entering the console of kodexplorer via `docker exec -ti kodexplorer bash`

```
bash-5.0# curl -I  https://172.21.0.3/web-apps/apps/api/documents/api.js
curl: (7) Failed to connect to 172.21.0.3 port 443: Connection refused

bash-5.0# curl -I  https://172.21.0.3:8000/web-apps/apps/api/documents/api.js
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number


bash-5.0# curl -I  http://172.21.0.3/web-apps/apps/api/documents/api.js
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 04 May 2020 19:41:19 GMT
Content-Type: application/javascript
Content-Length: 32375
Last-Modified: Mon, 06 Apr 2020 14:48:03 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "5e8b4123-7e77"
Expires: Mon, 04 May 2020 19:41:18 GMT
Cache-Control: no-cache
Accept-Ranges: bytes


bash-5.0# curl -I  http://172.21.0.3:8000/web-apps/apps/api/documents/api.js
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Cache-Control: public, max-age=604800
Last-Modified: Mon, 06 Apr 2020 14:48:03 GMT
ETag: W/"7e77-1714ff670b8"
Content-Type: application/javascript; charset=UTF-8
Content-Length: 32375
Date: Mon, 04 May 2020 19:41:26 GMT
Connection: keep-alive
```
 
So apparently this should be right:
![image](https://user-images.githubusercontent.com/837902/81006817-6a4a3f00-8e50-11ea-992d-f8b3916e85f6.png)

but results in this:

![image](https://user-images.githubusercontent.com/837902/81006777-56064200-8e50-11ea-890b-6f605177ae12.png)


If I use this:
![image](https://user-images.githubusercontent.com/837902/81006893-8a79fe00-8e50-11ea-9de7-b9d5afbd0146.png)


this is the result:
![image](https://user-images.githubusercontent.com/837902/81007040-cd3bd600-8e50-11ea-90e3-87017177c827.png)
